### ISSUE TITLE
server-side scripting error V8js.php failed to open stream

### ISSUE THREAD

**Issue by delebash** [dreamfactorysoftware/dsp-core#63] opened 2014-12-05 06:51 UTC
Windows 7 x64
Bitnami 1.8.2
Can't get any server-side scripting to work, it errors saying  V8js.php failed to open stream. No such file or directory.  Attached is the full error.
![2014-12-05_01-28-58](https://cloud.githubusercontent.com/assets/2220160/5312061/4f6162d8-7c20-11e4-9750-51c935a96daa.jpg)

Error file on OneDrive, github really needs to support file attachments
https://onedrive.live.com/redir?resid=EEFF875126810EAE!1096&authkey=!AG-kuzjL7a92bL4&ithint=file%2ctxt

**Comment by jstablesdf** [comment] 2015-01-20 16:43
We checked in with Bitnami, and they informed us the currently stable version for installing Bitnami modules is LAMP/MAMP/WAMP 5.4. (Since they plan to move to PHP 5.5 soon, modules are also tested against 5.5, although that is still considered a Dev stack for the time being.)

Since versions later than 5.4 are Dev, they do not support modules on top of them officially right now. The V8js module is confirmed to be included and working in the 5.4 and 5.5 stacks. You encountered this issue because you attempted to add DSP to a Bitnami stack that they do not support the addition of modules to at this time.

**Closed** 2015-01-20 16:44 UTC
Labels: invalid
