### ISSUE TITLE
DreamFactory as api gateway for microservices

### ISSUE THREAD

**Issue by bazani** [dreamfactorysoftware/dsp-core#82] opened 2015-05-29 13:29 UTC
Hi there! I'm searching for an api gateway for my new project. Can DreamFactory receive an request for one endpoint (/api/blog/post/123) and then consume multiples services (www.my.api/v1/post/123 and www.my.api/v1/comments?post-id=123) and wrap the response in one JSON object and only then answer that request for the endpoint?

**Comment by jstablesdf** [comment] 2015-05-29 14:03
Hi @bazani, I'm not sure this is an issue with our code. Can you let me know if you would just like to talk to our team about possibilities with DSP, or if this actually is a report of a code problem?

**Comment by jstablesdf** [comment] 2015-06-02 17:43
Since this is not confirmed as a bug, I am closing this issue. Feel free to contact us at dspsupport@dreamfactory.com if you have questions or further details on how this is a bug.

**Comment by df-jablan** [comment] 2015-06-02 21:54
This can be done using server-side scripting. 

Create a script which makes the multiple calls and bundles the responses. The result of the script is then returned to the client/caller/requester. To make outbound calls from server-side scripts, use the `platform.api` method but specify a fully qualified URL vs. an internal API call.

For example (untested, seat-of-my-pants-code, you've been warned):

```javascript
/**
 * Get each of the feeds and build a response object
 */
function _getResponses() {
	var _responses = [];

	var _feeds = [{
		'id':  'posts',
		'url': ['http://www.my.api/v1/post/123']
	}, {
		'id':  'comments',
		'url': 'http://www.my.api/v1/post/123?post-id=123'
	}];

	_.each(_feeds, function(feed) {
		_responses.push({
			'id':      feed.id,
			'content': platform.get(feed.url) || null
		});
	});

	return _responses;
}

return _getResponses();
```

There are myriad ways of accomplishing this in Javascript. That's just one suggestion. Since I have no idea what you want your response packet to look like. So just map your returned array/object to whatever you want.

**Closed** 2015-06-02 21:58 UTC
Labels: question

**Comment by bazani** [comment] 2015-06-02 22:01
Thanks, that is just what i need for my project.
