### ISSUE TITLE
Is there a way to configure a "Naming strategy" to translate table and field names from-to database<=>API

### ISSUE THREAD

**Issue by mnesarco** [dreamfactorysoftware/dsp-core#92] opened 2015-07-23 16:39 UTC
Hi, 
I use a very strict naming convention in my database, but it is not always good to use the same naming convention in json documents, url query parameters, etc... Is there a general way to apply a name transformation for all objects when serializing/deserializing json and also in url paths, query parameters etc.... so no real database names are exposed.

Example table:

mod_contact (
  id_ serial,
  name_ varchar,
  audit_user_id_ integer
);

Should be serialized to and unserialized from json (example):
{ "id": 232, "name":"test", "auditUserId":1 }

The service url: /db/Contact instead of /db/mod_contact

Maybe something like:

    interface SQLNamingStrategy {
       public String table_name_sql_to_api(String v);
       public String table_name_api_to_sql(String v);
       public String column_name_sql_to_api(String v);
       public String column_name_api_to_sql(String v);
       ...
    }

So we can implement it and register somewhere...
What do you think? is it possible?

**Comment by jstablesdf** [comment] 2015-09-09 16:51
This sort of thing isn't available in [dsp-core](https://github.com/dreamfactorysoftware/dsp-core), also known as DreamFactory 1.x, unless you incorporate or contribute it to the codebase yourself (which you are welcome to do!).

We are adding table- and field- level aliasing as a feature in [DreamFactory 2.0](https://github.com/dreamfactorysoftware/dreamfactory), which is already in public beta.

Closing this issue as it's not a bug or a planned feature in the 1.x codebase.

**Closed by jstablesdf** 2015-09-09 16:51 UTC
Labels: v2
