### ISSUE TITLE
permissions problem

### ISSUE THREAD

**Issue by Janwout** [dreamfactorysoftware/dsp-core#100] opened 2015-09-07 14:37 UTC
When using commands below with an admin user, i get the data

`{"record":[{"dept_no":"d009","dept_name":"Customer Service"},{"dept_no":"d005","dept_name":"Development"},{"dept_no":"d002","dept_name":"Finance"},{"dept_no":"d003","dept_name":"Human Resources"},{"dept_no":"d001","dept_name":"Marketing"},{"dept_no":"d004","dept_name":"Production"},{"dept_no":"d006","dept_name":"Quality Management"},{"dept_no":"d008","dept_name":"Research"},{"dept_no":"d007","dept_name":"Sales"}]}`

but when i use a user with a role. The role has: service > employees, component > * and access > get. The response is:
`{"error":[{"context":null,"message":"Access to application 'employees' is not provisioned for this user's role.","code":403}]}`

Below, the two curl command used for each user.
`curl -i -k -3 -X POST http://localhost:8080/rest/user/session  -H "X-DreamFactory-Application-Name: employees"  -d '{ "email" : "janwout@gmail.com", "password" : "************" }'`

`curl -v -i -k -3 -X GET http://localhost:8080/rest/employees/departments?app_name=employees  -H "X-DreamFactory-Session-Token: 9t2ct96jts4m469u6kjeufpfr4"`

When i look at the dreamfactory table df_sys_role_service_access, I see in column Access, only No Access.

**Comment by Janwout** [comment] 2015-09-08 11:46
When i create an app with the same name it works as expected. Is this by design?

**Comment by jstablesdf** [comment] 2015-09-08 12:11
Yes, this is by design. Your app name or API key is required for every call, and the user's role must be given access to use that app name / API key before a call that provides it will succeed. It appears you created a service named "employees" and later an app named "employees," which might be part of the confusion. I recommend reviewing the documentation:

 - https://github.com/dreamfactorysoftware/dsp-core/wiki/Common-Headers-Parameters
 - https://github.com/dreamfactorysoftware/dsp-core/wiki/cURL-Examples
 - https://github.com/dreamfactorysoftware/dsp-core/wiki/REST-API-Authentication
 - https://github.com/dreamfactorysoftware/dsp-core/wiki/Tutorials
 - https://github.com/dreamfactorysoftware/dsp-core/wiki/Screencasts

**Comment by jstablesdf** [comment] 2015-09-08 12:11
Closing, not a bug.

**Closed by jstablesdf** 2015-09-08 12:11 UTC
Labels: invalid
